controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_questions_index:
    path: /questions
    controller: \App\Controller\QuestionsController::index
    methods: GET

app_questions_new:
    path: /questions/new
    controller: \App\Controller\QuestionsController::new
    methods: GET|POST

app_questions_show:
    path: /questions/{id}
    controller: \App\Controller\QuestionsController::show
    methods: GET

app_questions_edit:
    path: /questions/{id}/edit
    controller: \App\Controller\QuestionsController::edit
    methods: GET|POST

app_questions_delete:
    path: /questions/{id}
    controller: \App\Controller\QuestionsController::delete
    methods: POST